### ISSUE TITLE
How to set up ssl.verification_mode=none just like in filebeat

### ISSUE THREAD

**Issue by tony9527167** [confluentinc/kafka-connect-elasticsearch#861]
filebeat supports disable SSL verification with configuration 

```yaml
output.elasticsearch:
  hosts: ["https://localhost:9200"]
  username: "elastic"
  password: "elastic"
  ssl.verification_mode: "none"
```

How to set it up in kafka-connect-elasticsearch? 

```properties
name=elasticsearch-sink
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=1
topics=test-elasticsearch-sink
key.ignore=true
connection.url=https://localhost:9200
connection.username=elastic
connection.password=elastic
type.name=kafka-connect

# no option likes ssl.verification_mode?
```
